# Generated by Django 5.2.5 on 2025-08-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='default_post_privacy',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('private', 'Private')], default='public', help_text='Default privacy level for new posts.', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications for key actions.'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='Who can view your profile.', max_length=10),
        ),
    ]
